### ISSUE TITLE
How to use ExAdmin.Show with Exfile ?

### ISSUE THREAD

**Issue by loongmxbt** [smpallen99/ex_admin#199]
I've checked the docs https://hexdocs.pm/exfile/Exfile.Phoenix.Helpers.html#content
and https://hexdocs.pm/ex_admin/ExAdmin.Show.html but cannot do this right.

In doc, there is
```
row :image, [image: true, height: 100], &(ExAdminDemo.Image.url({&1.image, &1}, :thumb))
```
Is `:image` just the row name, and `:thumb` from the ecto field?
Whats the param passed to &1 here?
How does `[image: true, height: 100]` deal with `ExAdminDemo.Image.url`?

```
schema "papers" do
    field :title, :string
    field :file, Exfile.Ecto.File
```
file is `Exfile.Ecto.File` and cannot directly show in ExAdmin, so I need to customize the show row.

```
row :file, [], &(Exfile.Phoenix.Helpers.exfile_path(&1))
```

The specs are
```
exfile_path(Exfile.File.t, exfile_path_opts) :: String.t
exfile_url(Exfile.File.t, exfile_path_opts, []) :: String.t
exfile_url(Plug.Conn.t | Phoenix.Socket.t | URI.t, Exfile.File.t, exfile_path_opts) :: String.t
exfile_url(atom, Exfile.File.t, exfile_path_opts) :: String.t
```

So how to use `exfile_path` or `exfile_url` in ExAdmin.show? Thanks!

**Comment by smpallen99** [comment]
@loongmxbt I have not used ex_file, so I can't give you a specific answer. In the example above, the `:image` parameter is only used for the label since you are providing a fun to fetch the field. The `&1` will be the model. However, the `ExAdminDemo.Image.url({&1.image, &1}, :thumb)` from the example is using the Arc API. So, you will need to replace that with the API for exfile. If the field in the model is `file`, then you should try `row :image, [image: true, height: 100], &(exfile_url(&1.file))`

**Comment by loongmxbt** [comment]
Thanks!
```
# Here &1 represents the paper, so we need to use &1.file
# https://github.com/smpallen99/ex_admin/issues/199
# https://github.com/keichan34/exfile/blob/7441e1b35728b9c27f486ccf023ba327ca0f5d73/test/exfile/phoenix/helpers_test.exs
       
import Exfile.Phoenix.Helpers
row :file_path, &(exfile_path(&1.file))
row :file_url, &(exfile_url(conn, &1.file, filename: "PID#{&1.id}-CID#{&1.topic.id}"))
```
