### ISSUE TITLE
Demo links resolve a 502 error

### ISSUE THREAD

**Issue by natecox** [smpallen99/ex_admin#352]
Currently, both of the demo links on the readme point to pages that return a 502 server error.

**Comment by agustif** [comment]
I would expect this to be like it since both ex_admin, and coherence are being fully worked by @smpallen99 to be phoenix 1.3 compatible, so probably new demos are coming in a few weeks...

That's what I would expect, at least, it would be nice a -deploy to heroku- instead of a random instance, so anyone interested in playing around can do so on free hardware.

**Comment by smpallen99** [comment]
Sorry, I was working on the server the other day to install a new app for a client. I forgot to startup the demos. They are working now. Thanks for letting me know @natecox

**Comment by smpallen99** [comment]
I have them hosted on a Digital Ocean instance with nginx handling the subdomain virtual host stuff.

**Comment by agustif** [comment]
I have recently used gatling (nginx wasn't working how I was doing it) and found it really cool for heroku-like deployment.

I will try and do some demo once the 1.3phx branch is released in master, I need to practice associations anyway!
