### ISSUE TITLE
Hex Package

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#56]
Hello. Thank you for your superb package. I have managed to get it to work with less than 10 minutes. And I will use it in production. 

Everything is fine except the installation process. I don't really trust installing my deps from github. As there's no guaranty for it to work straight from the `master` branch. So the question is:

Why don't you create a hex package?

**Comment by smpallen99** [comment]
I've been hesitant on releasing to hex since until I was fairly sure it was ready. I've been working on a fairly large refactor to support a brand new look and feel (theme) as well as providing support for the existing one. 

However, perhaps its time to release the current version. I'll see If I have some time this week to look into moving this and its dependencies into hex.

**Comment by smpallen99** [comment]
@sobolevn Thanks for the push. ExAdmin and its dependencies have all been published to Hex.
